[phases.setup]
commands = [
  "npm install"
]

[phases.build]
commands = [
  "npm run build --configuration production"
]

[phases.start]
commands = [
  "npx serve -s dist/omera -l $PORT"
]

[env]
PORT = "3000"
